# Generated by Django 5.2.4 on 2025-07-12 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_git', '0001_initial'),
        ('apps_metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineageParseJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('git_repo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_git.gitrepo')),
            ],
        ),
        migrations.CreateModel(
            name='LineageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_script_path', models.CharField(blank=True, max_length=500)),
                ('relation_type', models.CharField(default='insert', max_length=50)),
                ('process_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='apps_metadata.hivetable')),
                ('target_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='apps_metadata.hivetable')),
            ],
            options={
                'unique_together': {('source_table', 'target_table', 'sql_script_path')},
            },
        ),
        migrations.CreateModel(
            name='ColumnLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(max_length=255)),
                ('target_column', models.CharField(max_length=255)),
                ('transformation', models.TextField(blank=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_lineages', to='apps_lineage.lineagerelation')),
            ],
            options={
                'unique_together': {('relation', 'source_column', 'target_column')},
            },
        ),
    ]
