# Generated by Django 5.2.4 on 2025-07-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_lineage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineageparsejob',
            name='parse_type',
            field=models.CharField(choices=[('full', 'Full Parse'), ('incremental', 'Incremental Parse'), ('full_overwrite', 'Full Overwrite Parse')], default='full', max_length=20),
        ),
    ]
