# Generated by Django 5.2.4 on 2025-07-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_git', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepo',
            name='ssl_verify',
            field=models.BooleanField(default=True, help_text='是否验证SSL证书，内网私有GitLab建议设为False'),
        ),
    ]
