# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_git', '0002_gitrepo_ssl_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepo',
            name='auth_type',
            field=models.CharField(choices=[('password', '用户名密码'), ('token', 'Token认证')], default='password', help_text='认证方式：密码或Token', max_length=10),
        ),
    ]