# Generated by Django 5.2.4 on 2025-07-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_git', '0004_gitrepo_access_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepo',
            name='successful_auth_format',
            field=models.CharField(blank=True, help_text='记录最后一次成功的认证格式，用于优化后续认证', max_length=50),
        ),
    ]