# Generated by Django 5.2.4 on 2025-07-13 09:36

import apps_metadata.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_metadata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiveAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='配置名称', max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=10000)),
                ('auth_type', models.CharField(choices=[('NONE', '无认证'), ('LDAP', 'LDAP认证'), ('KERBEROS', 'Kerberos认证')], default='NONE', max_length=20)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('kerberos_service_name', models.CharField(blank=True, default='hive', max_length=255)),
                ('principal', models.CharField(blank=True, help_text='Kerberos principal', max_length=255)),
                ('keytab_file', models.FileField(blank=True, help_text='Keytab文件', null=True, upload_to=apps_metadata.models.hive_auth_file_upload_path)),
                ('krb5_conf_file', models.FileField(blank=True, help_text='krb5.conf配置文件', null=True, upload_to=apps_metadata.models.hive_auth_file_upload_path)),
                ('custom_jar_files', models.TextField(blank=True, help_text='自定义JAR包文件路径列表，JSON格式存储')),
                ('default_database', models.CharField(default='default', max_length=255)),
                ('connection_timeout', models.IntegerField(default=30, help_text='连接超时时间（秒）')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hive_auth_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HiveJarFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='JAR文件显示名称', max_length=255)),
                ('file', models.FileField(help_text='JAR文件', upload_to=apps_metadata.models.hive_auth_file_upload_path)),
                ('description', models.TextField(blank=True, help_text='文件描述')),
                ('version', models.CharField(blank=True, help_text='版本号', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hive_jar_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
